# This is a basic workflow to help you get started with Actions
name: Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout other repo
        uses: actions/checkout@v3
        with:
          repository: retrorocket/blog-contents
          path: src/content/posts
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: restore node_modules cache
        uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('node_modules/.modules.yaml', 'node_modules/.astro/assets/**') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: restore ogp image cache
        uses: actions/cache/restore@v3
        id: restore-image-cache
        with:
          path: "public/og-images"
          key: ${{ runner.os }}-ogp-${{ hashFiles('public/og-images/**') }}
          restore-keys: |
            ${{ runner.os }}-ogp-
      - name: Install packages
        run: pnpm install
      - name: Run build
        run: pnpm run build
        env:
          PUBLIC_ALGOLIA_APPID: ${{ secrets.PUBLIC_ALGOLIA_APPID }}
          PUBLIC_ALGOLIA_APIKEY: ${{ secrets.PUBLIC_ALGOLIA_APIKEY }}
          PRIVATE_ALGOLIA_WRITE_KEY: ${{ secrets.PRIVATE_ALGOLIA_WRITE_KEY }}
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{secrets.DEPLOY_PATH}}
          remote_host: ${{secrets.SSH_HOSTNAME}}
          remote_port: ${{secrets.SSH_PORT}}
          remote_user: ${{secrets.SSH_USERNAME}}
          remote_key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: save node_modules cache
        uses: actions/cache/save@v3
        id: cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('node_modules/.modules.yaml', 'node_modules/.astro/assets/**') }}
      - name: save og-images cache
        uses: actions/cache/save@v3
        id: save-image-cache
        with:
          path: "dist/og-images"
          key: ${{ runner.os }}-ogp-${{ hashFiles('dist/og-images/**') }}
