# This is a basic workflow to help you get started with Actions
name: deploy-webhook-triger

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout other repo
        uses: actions/checkout@v3
        with:
          repository: retrorocket/blog-contents
          path: src/content/posts
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: rename images
        run: mv src/content/posts/_images src/content/posts/images
      - name: mv images
        run: mv src/content/posts/images public/
      - uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm install
      - name: Run build
        run: npm run build
        env:
          PUBLIC_ALGOLIA_APPID: ${{ secrets.PUBLIC_ALGOLIA_APPID }}
          PUBLIC_ALGOLIA_APIKEY: ${{ secrets.PUBLIC_ALGOLIA_APIKEY }}
          PRIVATE_ALGOLIA_WRITE_KEY: ${{ secrets.PRIVATE_ALGOLIA_WRITE_KEY }}
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude "/.well-known"
          path: dist/
          remote_path: ${{secrets.DEPLOY_PATH}}
          remote_host: ${{secrets.SSH_HOSTNAME}}
          remote_port: ${{secrets.SSH_PORT}}
          remote_user: ${{secrets.SSH_USERNAME}}
          remote_key: ${{secrets.SSH_PRIVATE_KEY}}

