# This is a basic workflow to help you get started with Actions
name: Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout src/content repo
        uses: actions/checkout@v4
        with:
          repository: retrorocket/blog-contents
          path: src/content/posts
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Restore node_modules cache
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('node_modules/.modules.yaml', 'node_modules/.astro/assets/**') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Restore ogp image cache
        uses: actions/cache/restore@v4
        id: restore-image-cache
        with:
          path: "dist/og-images"
          key: ${{ runner.os }}-ogp-${{ hashFiles('dist/og-images/**') }}
          restore-keys: |
            ${{ runner.os }}-ogp-
      - name: Move restored ogp image cache
        if: steps.restore-image-cache.outputs.cache-hit != 'true'
        run: |
          mv dist/og-images/* public/og-images
          rm -rf dist

      - name: Install packages
        run: pnpm install
      - name: Run build
        run: pnpm run build
        env:
          PUBLIC_ALGOLIA_APPID: ${{ secrets.PUBLIC_ALGOLIA_APPID }}
          PUBLIC_ALGOLIA_APIKEY: ${{ secrets.PUBLIC_ALGOLIA_APIKEY }}
          PRIVATE_ALGOLIA_WRITE_KEY: ${{ secrets.PRIVATE_ALGOLIA_WRITE_KEY }}
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{secrets.DEPLOY_PATH}}
          remote_host: ${{secrets.SSH_HOSTNAME}}
          remote_port: ${{secrets.SSH_PORT}}
          remote_user: ${{secrets.SSH_USERNAME}}
          remote_key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Save node_modules cache
        uses: actions/cache/save@v4
        id: cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('node_modules/.modules.yaml', 'node_modules/.astro/assets/**') }}
      - name: Save og-images cache
        uses: actions/cache/save@v4
        id: save-image-cache
        with:
          path: "dist/og-images"
          key: ${{ runner.os }}-ogp-${{ hashFiles('dist/og-images/**') }}
